#! /usr/bin/env python

"""\
%prog yodafile [aidafile]

Convert a YODA data file to the old AIDA data format.
"""

import yoda, os, sys, optparse

parser = optparse.OptionParser(usage=__doc__)
opts, args = parser.parse_args()

INFILE = None
OUTFILE = None

if len(args) == 1:
    INFILE = args[0]
    if INFILE.endswith(".yoda"):
        OUTFILE = INFILE.replace(".yoda", ".aida")
    else:
        OUTFILE = INFILE + ".aida"
    OUTFILE = os.path.basename(OUTFILE)
elif len(args) == 2:
    INFILE = args[0]
    OUTFILE = args[1]
else:
    sys.stderr.write("You must specify the YODA and AIDA file names\n")
    sys.exit(1)

analysisobjects = yoda.readYODA(INFILE)
yoda.writeAIDA(analysisobjects, OUTFILE)

